In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("C:/Users/lenyo/Documents/Datasets/Loan Default/train.csv")
df.head()

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Batch Enrolled,Interest Rate,Grade,Sub Grade,Home Ownership,...,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Application Type,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
0,65087372,10000,32236,12329.36286,59,BAT2522922,11.135007,B,C4,MORTGAGE,...,2.498291,0.793724,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12191.99692,59,BAT1586599,12.237563,C,D3,RENT,...,2.377215,0.974821,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22455,59,BAT2136391,12.545884,F,D4,MORTGAGE,...,4.316277,1.020075,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.15585,59,BAT2428731,16.731201,C,C3,MORTGAGE,...,0.107020,0.749971,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.92667,59,BAT5341619,15.008300,C,D4,MORTGAGE,...,1294.818751,0.368953,0,INDIVIDUAL,18,0,430,126029,22579,0

# 1.Understanding the Dataset #

###### ID-
###### Loan Amount-
###### Funded Amount-
###### Funded Amount investor-
###### Batch Enrolled-
###### Interest Rate-
###### Term-
###### Grade-
###### SubGrade-
###### Home Ownership-
###### Employment Duration-
###### Verification Status-
###### Payment Plan-
###### Loan title-
###### Debit to Income-
###### Delinquency -two years -
###### Inquires - six months -
###### Open Account- 
###### Public Record-
###### Revolving Balance-
###### Revolving Utilities-
###### Total Accounts-
###### Initial List Status- 
###### Total Received Interest-
###### Total Received Late Fee-
###### Recoveries-
###### Collection Recovery Fee-
###### Collection 12 months Medical-
###### Application Type-
###### Last week Pay-
###### Accounts Delinquent-
###### Total Collection Amount-
###### Total Current Balance-
###### Total Revolving Credit Limit-
###### Loan Status-

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67463 entries, 0 to 67462
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            67463 non-null  int64
 1   Loan Amount                   67463 non-null  int64
 2   Funded Amount                 67463 non-null  int64
 3   Funded Amount Investor        67463 non-null  float64
 4   Term                          67463 non-null  int64
 5   Batch Enrolled                67463 non-null  object
 6   Interest Rate                 67463 non-null  float64
 7   Grade                         67463 non-null  object
 8   Sub Grade                     67463 non-null  object
 9   Home Ownership                67463 non-null  object
 10  Employment Duration           67463 non-null  float64
 11  Verification Status           67463 non-null  object
 12  Payment Plan                  67463 non-null  object
 13  Loan Title                    67463 non-null  object
 14  Debit to Income               67463 non-null  float64
 15  Delinquency - two years       67463 non-null  int64
 16  Inquires - six months         67463 non-null  int64
 17  Open Account                  67463 non-null  int64
 18  Public Record                 67463 non-null  int64
 19  Revolving Balance             67463 non-null  int64
 20  Revolving Utilities           67463 non-null  float64
 21  Total Accounts                67463 non-null  int64
 22  Initial List Status           67463 non-null  object
 23  Total Received Interest       67463 non-null  float64
 24  Total Received Late Fee       67463 non-null  float64
 25  Recoveries                    67463 non-null  float64
 26  Collection Recovery Fee       67463 non-null  float64
 27  Collection 12 months Medical  67463 non-null  int64
 28  Application Type              67463 non-null  object
 29  Last week Pay                 67463 non-null  int64
 30  Accounts Delinquent           67463 non-null  int64
 31  Total Collection Amount       67463 non-null  int64
 32  Total Current Balance         67463 non-null  int64
 33  Total Revolving Credit Limit  67463 non-null  int64
 34  Loan Status                   67463 non-null  int64
dtypes: float64(9), int64(17), object(9)
memory usage: 18.0+ MB

In [7]:
df.describe()

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Interest Rate,Employment Duration,Debit to Income,Delinquency - two years,Inquires - six months,...,Total Received Late Fee,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
count,6.746300e+04,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,...,67463.000000,67463.000000,67463.000000,67463.000000,67463.000000,67463.0,67463.000000,6.746300e+04,67463.000000,67463.000000
mean,2.562761e+07,16848.902776,15770.599114,14621.799323,58.173814,11.846258,80541.502522,23.299241,0.327127,0.145754,...,1.143969,59.691578,1.125141,0.021301,71.163260,0.0,146.467990,1.595739e+05,23123.005544,0.092510
std,2.109155e+07,8367.865726,8150.992662,6785.345170,3.327441,3.718629,45029.120366,8.451824,0.800888,0.473291,...,5.244365,357.026346,3.489885,0.144385,43.315845,0.0,744.382233,1.390332e+05,20916.699999,0.289747
min,1.297933e+06,1014.000000,1014.000000,1114.590204,36.000000,5.320006,14573.537170,0.675299,0.000000,0.000000,...,0.000003,0.000036,0.000036,0.000000,0.000000,0.0,1.000000,6.170000e+02,1000.000000,0.000000
25%,6.570288e+06,10012.000000,9266.500000,9831.684984,58.000000,9.297147,51689.843335,16.756416,0.000000,0.000000,...,0.021114,1.629818,0.476259,0.000000,35.000000,0.0,24.000000,5.037900e+04,8155.500000,0.000000
50%,1.791565e+07,16073.000000,13042.000000,12793.682170,59.000000,11.377696,69335.832680,22.656658,0.000000,0.000000,...,0.043398,3.344524,0.780141,0.000000,68.000000,0.0,36.000000,1.183690e+05,16733.000000,0.000000
75%,4.271521e+07,22106.000000,21793.000000,17807.594120,59.000000,14.193533,94623.322785,30.048400,0.000000,0.000000,...,0.071884,5.453727,1.070566,0.000000,105.000000,0.0,46.000000,2.283750e+05,32146.500000,0.000000
max,7.224578e+07,35000.000000,34999.000000,34999.746430,59.000000,27.182348,406561.536400,39.629862,8.000000,5.000000,...,42.618882,4354.467419,166.833000,1.000000,161.000000,0.0,16421.000000,1.177412e+06,201169.000000,1.000000

In [8]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
67458    False
67459    False
67460    False
67461    False
67462    False
Length: 67463, dtype: bool

# 2.Data Cleaning #

In [37]:
Employement_duration =df[df.columns[10]].astype(int)                     #Since the employment duration units were not give, i took it to be in terms of
Employment_duration = (Employement_duration / 24)/365                    # Hours worked
df[df.columns[10]] = Employment_duration.astype(int)
df[df.columns[10]]

0        20
1         4
2        10
3        12
4         5
         ..
67458     9
67459     7
67460     3
67461    11
67462    12
Name: Employment Duration, Length: 67463, dtype: int32

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67463 entries, 0 to 67462
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            67463 non-null  int64
 1   Loan Amount                   67463 non-null  int64
 2   Funded Amount                 67463 non-null  int64
 3   Funded Amount Investor        67463 non-null  float64
 4   Term                          67463 non-null  int64
 5   Batch Enrolled                67463 non-null  object
 6   Interest Rate                 67463 non-null  float64
 7   Grade                         67463 non-null  object
 8   Sub Grade                     67463 non-null  object
 9   Home Ownership                67463 non-null  object
 10  Employment Duration           67463 non-null  int32
 11  Verification Status           67463 non-null  object
 12  Payment Plan                  67463 non-null  object
 13  Loan Title                    67463 non-null  object
 14  Debit to Income               67463 non-null  float64
 15  Delinquency - two years       67463 non-null  int64
 16  Inquires - six months         67463 non-null  int64
 17  Open Account                  67463 non-null  int64
 18  Public Record                 67463 non-null  int64
 19  Revolving Balance             67463 non-null  int64
 20  Revolving Utilities           67463 non-null  float64
 21  Total Accounts                67463 non-null  int64
 22  Initial List Status           67463 non-null  object
 23  Total Received Interest       67463 non-null  float64
 24  Total Received Late Fee       67463 non-null  float64
 25  Recoveries                    67463 non-null  float64
 26  Collection Recovery Fee       67463 non-null  float64
 27  Collection 12 months Medical  67463 non-null  int64
 28  Application Type              67463 non-null  object
 29  Last week Pay                 67463 non-null  int64
 30  Accounts Delinquent           67463 non-null  int64
 31  Total Collection Amount       67463 non-null  int64
 32  Total Current Balance         67463 non-null  int64
 33  Total Revolving Credit Limit  67463 non-null  int64
 34  Loan Status                   67463 non-null  int64
dtypes: float64(8), int32(1), int64(17), object(9)
memory usage: 17.8+ MB